### ISSUE TITLE
Some problems about how to acquire the objects type by " Entity Set Type Induction"

### ISSUE THREAD

**Issue by CreaterLL** [c-box/LANKA#1]
Hi,thank you for your open sourse of the thesis,and your method to investigate the MLM behaviour is quite exhaustive. i'm very interested in your excited work,however ,i encounted some confusion about the   " Entity Set Type Induction" module.
①To acquire my objects type ,Which files do I need to execute sequentially?
②What's means about the  "wikidata_tuples_p31" and "wikidata_tuples_p279", in order to figure this out, what information I need to refer to.
③Do you have any suggestions (or method guidance) for object type recognition for my own task needs?
Thank you very much!

**Comment by c-box** [comment]
Hello, thanks for your appreciation. 

In fact, the "Entity Set Type Induction" algorithm requires searching on all the tuples of relation [P31(instance of)](https://www.wikidata.org/wiki/Property:P31) and P279(subclass of) on Wikidata. In our work, we imported the entire Wikidata into ElasticSearch, which requires a lot of time and storage space, so we only provide the required intermediate files in the "data/type_file" folder. And the algorithm details are described in Section 4.2.

Would you like to acquire the entity set type of the entity set of your own data? If so, you need to build a corresponding ES index, and then execute the following function
https://github.com/c-box/LANKA/blob/5b55721bff5b4399f88e3ebf5ea6873def6f8d8a/case_based/case_utils.py#L358

Please let me know if you have other questions.

**Comment by CreaterLL** [comment]
Thank you very much for your answer, I'll give it a try !

**Comment by c-box** [comment]
You're welcome!  By the way, the "wikidata_tuples_p31" and "wikidata_tuples_p279" are two ES indexes including the tuples of P31 and P279 separately.
